/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_home_callcviajnidemo_jni_ShowLuckyNumberJni */

#ifndef _Included_com_home_callcviajnidemo_jni_ShowLuckyNumberJni
#define _Included_com_home_callcviajnidemo_jni_ShowLuckyNumberJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_home_callcviajnidemo_jni_ShowLuckyNumberJni
 * Method:    getTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_home_callcviajnidemo_jni_ShowLuckyNumberJni_getTitle
  (JNIEnv *, jobject);

/*
 * Class:     com_home_callcviajnidemo_jni_ShowLuckyNumberJni
 * Method:    getLuckyNumber
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_home_callcviajnidemo_jni_ShowLuckyNumberJni_getLuckyNumber
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
